apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-project
  template:
    metadata:
      labels:
        app: mlops-project
    spec:
      containers:
      - name: mlops-project
        image: shayancyan/mlops-project:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          python src/train_model.py
          echo "Completed training, entering sleep mode"
          sleep infinity
        ports:
        - containerPort: 5000
