name: CI

# Trigger on pushes and PRs to dev
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install dependencies + DVC
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      # 4. Pull the dataset via DVC
      - name: DVC pull
        run: dvc pull

      # 5. Lint your code
      - name: Lint with flake8
        run: flake8 src tests

      # 6. Run unit tests
      - name: Test with pytest
        run: pytest --maxfail=1 --disable-warnings -q
